### ISSUE TITLE
Guide for webgl deploy

### ISSUE THREAD

**Issue by inyourpc** [Unity-Technologies/com.unity.multiplayer.samples.coop#734]
Is there any guide with which we can build this example in webgl.
Transport services that are recommended should be mentioned here as well.

**Comment by SamuelBellomo** [comment]
Whenever (if ever) NGO and UTP support webgl and websockets, we'll look into it as well then. But since community transports are not officially supported by Unity, we won't include those in boss room unfortunately. We'll keep you posted on discord and forums if there's any updates on this.
You can also checkout our Netcode repo to see our current development on this.
