### ISSUE TITLE
Why did you create your own MessagePipe when there is already a nice framework for it? 

### ISSUE THREAD

**Issue by marcobethkeskyered** [Unity-Technologies/com.unity.multiplayer.samples.coop#793]
It looks like you guys got the same structure, so just wanted to know why :) 

https://github.com/Cysharp/MessagePipe#unity

**Comment by SamuelBellomo** [comment]
Yeah we considered MessagePipe and chose custom implementation. Since we have a custom networked message channel, we would have had to implement custom logic for MessagePipe anyway (in filters if I recall MP's appellation correctly). Our usage was super simple and it was faster to just do it ourselves without taking on yet another 3rd party lib. With a full production project, with a bunch of different gameplay elements and maps and characters and abilities, I think I would have considered MP instead, it's more feature rich than our barebone implementation.

**Comment by SamuelBellomo** [comment]
@marcobethkeskyered hope this answered your question, if you have more questions in general on samples, don't hesitate to hit us up on Discord https://discord.gg/buMxnnPvTb in the #samples channel. I'll close this issue for now.

**Comment by marcobethkeskyered** [comment]
Ok thank you very much!!
