### ISSUE TITLE
Feedback for docs/advanced-topics/object-pooling.md

### ISSUE THREAD

**Issue by treyDarling** [Unity-Technologies/com.unity.multiplayer.samples.coop#838]
the following line on the object pooling example give an error.

// Register Netcode Spawn handlers
            NetworkManager.Singleton.PrefabHandler.AddHandler(prefab, new PooledPrefabInstanceHandler(prefab, this));

**Comment by LPLafontaineB** [comment]
Do you have more context? Did you take this sample code and add it to your personal project? Did you make any changes to the code? Which version of Netcode for GameObjects and which editor version did you use?

This error should not happen if using the code as is, since `PooledPrefabInstanceHandler` implements the `INetworkPrefabInstanceHandler` interface

**Comment by treyDarling** [comment]
yes I added it to my project. no changes were made. netcode version 1.0.2 editor version 2022.1.13f1

**Comment by LPLafontaineB** [comment]
Do you have the full callstack?

**Comment by LPLafontaineB** [comment]
Can you confirm that in your project, the class `PooledPrefabInstanceHandler` implements the `INetworkPrefabInstanceHandler` interface?

If indeed that is the case, without more information, I will not be able to help you. Can you look at the template we have for submitting issues and fill out all the required sections? Also, if you can reproduce it and share the callstack of the error, that would be helpful. Also, if you could share a zip of a minimal project showcasing the same issue that would also help.

**Comment by LPLafontaineB** [comment]
I found your issue. It is because of your `NetworkHandler.cs` where you defined another interface named `INetworkPrefabInstanceHandler`, so the compiler used this definition in `NetworkObjectPool` instead of the one defined in the namespace `Unity.Netcode` by Netcode for GameObjects. If you simply delete the `NetworkHandler.cs` file, or rename the interface you defined within it, the error will disappear.

**Comment by treyDarling** [comment]
deleting INetworkPrefabInstanceHandler worked
