### ISSUE TITLE
'NetworkManager' does not contain a definition for 'OnClientStarted'

### ISSUE THREAD

**Issue by zhuziying** [Unity-Technologies/com.unity.multiplayer.samples.coop#847]
Library\PackageCache\com.unity.multiplayer.samples.coop@a4cafe2062\Utilities\SceneManagement\SceneLoaderWrapper.cs(83,32): error CS1061: 'NetworkManager' does not contain a definition for 'OnClientStarted' and no accessible extension method 'OnClientStarted' accepting a first argument of type 'NetworkManager' could be found (are you missing a using directive or an assembly reference?)

![image](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/assets/4710245/69fe1ca9-650e-48e9-b4ab-bb00cfe43c85)

**Comment by LPLafontaineB** [comment]
Thank you for the feedback @zhuziying ! This is a dependencies issue in the Utilities package, it should have been updated to require Netcode for GameObjects v1.4.0 in our previous release but wasn't. The dependencies will be fixed in our next release, but in the meantime if you update your project to use NGO version 1.4.0 or up it should fix your issue. Alternatively, you can use an earlier version of the utilities package using the v2.0.4 tag

**Comment by zhuziying** [comment]
@LPLafontaineB thank u very much
