### ISSUE TITLE
bug: Host name !supported (only ip)

### ISSUE THREAD

**Issue by dylanh724** [Unity-Technologies/com.unity.multiplayer.samples.coop#857]
**Describe the bug**
One cannot enter a host name; only an IP

**To Reproduce**
1. Join game
2. Enter host:port (rather than ip:port)

**Expected behavior**
Should have connected the same as IP

**Environment (please complete the following information):**
 - OS: Win11
 - Unity Version: 2022 LTS
 - BossRoom Version: Current clone as of 08/15/2023

**Additional context**
Easily resolved by parsing to IPAddress via `Dns` namespace without any additional libs, upon detection of a host instead of ip (contains [a-z])

Since this is an industry standard, much like TLS (all competitors support this), this issue should be treated as a bug and not a feature request.

**Comment by LPLafontaineB** [comment]
Hi Dylan! Thank you for flagging this. This is already in our backlog and we do plan to implement this functionality in Netcode for GameObjects, but we don't know yet when it will be available

**Comment by LPLafontaineB** [comment]
Hi again! I will be closing this issue since this functionality, while being in the backlog for future consideration, is not currently part of the NGO roadmap, and so we cannot say when/if we would be able to include this functionality within the Boss Room sample.
I would recommend keeping an eye on our [Multiplayer Roadmap](https://unity.com/roadmap/unity-platform/multiplayer-networking) and [Discord Community](https://discord.com/channels/449263083769036810/450736485323243541) where we share regular updates when things are moved into active development.
